version: '3.8'

services:
  db:
    image: postgres:17
    container_name: bookstore_db
    restart: always
    env_file:
      - .env

    ports:
      - 5432:5432
    volumes:
      - bookstore_db_data:/var/lib/postgresql/data
    
volumes:
  bookstore_db_data: