basePath: /api/v1
host: bookstore.mkruse.xyz
info:
  contact:
    name: Maximilian Kruse
    url: https://github.com/maxkruse
  description: This is a sample server for a bookstore server with included LLM functionality.
  license:
    name: No License
  title: LM Studio Website API
  version: "1.0"
paths: {}
swagger: "2.0"
