# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup Swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Init Swag Docs
      run: swag init --dir ./cmd/server/,./internal/api/v1/,./internal/models/dtos/

    - name: Build the binary
      run: go build -o ./tmp/main.exe ./cmd/server/main.go 
